language: objective-c
matrix:
    include:
        - osx_image: xcode10

script:
    - xcodebuild build test -project HashKitDemo.xcodeproj -scheme HashKit -configuration Debug -destination "platform=iOS Simulator,name=iPhone X"

